### ISSUE TITLE
Hover Question

### ISSUE THREAD

**Issue by tsyroid** [David-Kunz/vim#2]
Not an issue, David, just a how-the-heck question. Couldn't find any other way to contact you.

I've been working through your `init.lua` file, learning from your work.

But I can't for the life of me find what you did in your code to achieve the "ghosted" git commit information at the end of a line when the cursor is active. I've been searching for a week now, trying bits and bobs in my own config file, and I'm getting exactly nowhere. Could you help a guy out please before I lose any more hair?

[2022-01-30 22:00] OK, got it thanks. `git_blame` option under `neogit` config. You can close this.

**Comment by David-Kunz** [comment]
Hi @tsyroid ,

Thanks for reaching out to me!

Actually it's configured for `gitsigns`:

```lua
-- lewis6991/gitsigns.nvim
require('gitsigns').setup({
  current_line_blame = true
})
```

Best regards,
David
